pypi-sphinx_rtd_theme: Autospec creation for update from version 1.3.0 to version 2.0.0
Anthony (9):
      Release 2.0.0rc1 (#1510)
      Bump to next release 2.0.0rc2 (#1511)
      Release 2.0rc2 (#1520)
      Version bump for 2.0rc3 development (#1521)
      Release 2.0.0rc3 (#1535)
      Increment for next potential release (#1536)
      Release 2.0.0rc4 (#1538)
      Bump for next potential release, 2.0.0rc5 (#1539)
      Release 2.0 final (#1544)

Benjamin Balder Bach (1):
      Docs: Remove "git install" method from instructions (#1375)

Dmitry Shachnev (2):
      Set data-content_root for Sphinx ≥ 7.2 (#1507)
      Fix AttributeError when one of `css_files` is a string (#1537)

Manuel Kaufmann (6):
      2.0 milestone: drop supported versions (#1500)
      Visual test with Firefox and tox (#1513)
      Remove Python2 leftovers (#1514)
      Docs: update Read the Docs config (#1518)
      Use `css_tag` helper to inject CSS files (#1519)
      Add support for `docutils==0.20.x` (#1517)

Mathieu Leplatre (1):
      Fix #1522: fix `'str' object has no attribute 'attributes'` (#1528)